### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by M4N0J-KUM4R** [Ur-Maso/Macrorify-language-support#1]
can you explain how can i install this my vscode

**Comment by Sinfolke** [comment]
Clone the repository and open that folder in vscode.
Then you should run debugging (f5 button) and there will open one more window with extension included. Then you can create a file with extension ".macr" or ".macrorify" and then write your code there. You'll have highlighted code and some syntax checks. Also intellisense including variables and functions. Sadly i did syntax checks by regex so they may not find all or sometimes do wrong.

For more information see [Your first vscode extension](https://code.visualstudio.com/api/get-started/your-first-extension)
